#ifndef CINDER__FRONT_END__LANGUAGE_FEATURES_H
#define CINDER__FRONT_END__LANGUAGE_FEATURES_H


typedef enum {
    CND_LANGFEAT_C = 1 << 1,
    CND_LANGFEAT_C99 = 1 << 2,
    CND_LANGFEAT_C11 = 1 << 3,
    CND_LANGFEAT_C17 = 1 << 4,
    CND_LANGFEAT_C23 = 1 << 5,
    CND_LANGFEAT_C29 = 1 << 6,

    CND_LANGFEAT_CND = 1 << 16,

    CND_LANGFEAT_HEXFLOAT = 1 << 26,
    CND_LANGFEAT_DIGRAPHS = 1 << 27,
    CND_LANGFEAT_LINE_COMMENT = 1 << 28,

    CND_LANGFEAT_MSVC = 1 << 29,
    CND_LANGFEAT_CLANG = 1 << 30,
    CND_LANGFEAT_GNU = 1 << 31,

    CND_LANGFEAT_STDC89 = CND_LANGFEAT_C,
    CND_LANGFEAT_STDC94 = CND_LANGFEAT_STDC89 | CND_LANGFEAT_DIGRAPHS,
    CND_LANGFEAT_STDC99 = CND_LANGFEAT_STDC94 | CND_LANGFEAT_C99 | CND_LANGFEAT_LINE_COMMENT | CND_LANGFEAT_HEXFLOAT,
    CND_LANGFEAT_STDC11 = CND_LANGFEAT_STDC99 | CND_LANGFEAT_C11,
    CND_LANGFEAT_STDC17 = CND_LANGFEAT_STDC11 | CND_LANGFEAT_C17,
    CND_LANGFEAT_STDC23 = CND_LANGFEAT_STDC17 | CND_LANGFEAT_C23,
    CND_LANGFEAT_STDC29 = CND_LANGFEAT_STDC23 | CND_LANGFEAT_C29,

    CND_LANGFEAT_GNUC89 = CND_LANGFEAT_STDC89 | CND_LANGFEAT_GNU | CND_LANGFEAT_LINE_COMMENT | CND_LANGFEAT_HEXFLOAT | CND_LANGFEAT_DIGRAPHS,
    CND_LANGFEAT_GNUC99 = CND_LANGFEAT_GNUC89 | CND_LANGFEAT_C99,
    CND_LANGFEAT_GNUC11 = CND_LANGFEAT_GNUC99 | CND_LANGFEAT_C11,
    CND_LANGFEAT_GNUC17 = CND_LANGFEAT_GNUC11 | CND_LANGFEAT_C17,
    CND_LANGFEAT_GNUC23 = CND_LANGFEAT_GNUC17 | CND_LANGFEAT_C23,
    CND_LANGFEAT_GNUC29 = CND_LANGFEAT_GNUC23 | CND_LANGFEAT_C29,

    CND_LANGFEAT_STDCND = CND_LANGFEAT_CND | CND_LANGFEAT_LINE_COMMENT,
} CndLanguageFeatures;


#endif /* CINDER__FRONT_END__LANGUAGE_FEATURES_H */
